/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioCard: typeof import('./src/components/AudioCard/index.vue')['default']
    BLCol: typeof import('./src/components/BLCol.vue')['default']
    BLRow: typeof import('./src/components/BLRow.vue')['default']
    BLTag: typeof import('./src/components/BLTag.vue')['default']
    copy: typeof import('./src/components/GWPdfViewer copy.vue')['default']
    DayNight: typeof import('./src/components/DayNight/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FsEstimatedVirtualList: typeof import('./src/components/FsEstimatedVirtualList.vue')['default']
    FsVirtualList: typeof import('./src/components/FsVirtualList.vue')['default']
    Fullscreen: typeof import('./src/components/Fullscreen/index.vue')['default']
    GWAudioPreview: typeof import('./src/components/GWAudioPreview.vue')['default']
    GWAvatar: typeof import('./src/components/GWAvatar.vue')['default']
    GWClassifyImage: typeof import('./src/components/GWClassifyImage.vue')['default']
    GWFlexContainer: typeof import('./src/components/GWFlexContainer.vue')['default']
    GWFlexMovieCard: typeof import('./src/components/GWFlexMovieCard.vue')['default']
    GWLogoCard: typeof import('./src/components/GWLogoCard.vue')['default']
    GWMusicSortableTable: typeof import('./src/components/GWMusicSortableTable.vue')['default']
    GWPdfViewer: typeof import('./src/components/GWPdfViewer.vue')['default']
    'GWPdfViewer copy': typeof import('./src/components/GWPdfViewer copy.vue')['default']
    GWPreviewImage: typeof import('./src/components/GWPreviewImage.vue')['default']
    GWPreviewVideo: typeof import('./src/components/GWPreviewVideo.vue')['default']
    GWResourceCard: typeof import('./src/components/GWResourceCard.vue')['default']
    GWSearchCondition: typeof import('./src/components/GWSearchCondition.vue')['default']
    GWSortableTable: typeof import('./src/components/GWSortableTable.vue')['default']
    GWTitleCard: typeof import('./src/components/GWTitleCard.vue')['default']
    GWTitleImageCard: typeof import('./src/components/GWTitleImageCard.vue')['default']
    GWVirtualWaterFall: typeof import('./src/components/GWVirtualWaterFall.vue')['default']
    GWWaterFall: typeof import('./src/components/GWWaterFall.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    LinkGroup: typeof import('./src/components/LinkGroup/index.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/index.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
    ToolBox: typeof import('./src/components/ToolBox/index.vue')['default']
    ToTop: typeof import('./src/components/ToTop/index.vue')['default']
    Wave: typeof import('./src/components/Wave/index.vue')['default']
  }
}
